# Generated by Django 4.0.3 on 2024-05-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0006_books_cover_image_books_download_books_file_videos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'List of Video'},
        ),
        migrations.AlterField(
            model_name='books',
            name='download',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='download',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2, null=True),
        ),
    ]
