# Generated by Django 4.0.3 on 2024-05-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0007_alter_videos_options_alter_books_download_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('topic', models.CharField(max_length=250)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'List of Inquiries',
            },
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'List of Videos'},
        ),
        migrations.AlterField(
            model_name='videos',
            name='download',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
